### ISSUE TITLE
Синтаксическая ошибка в downloader.py

### ISSUE THREAD

**Issue by TkachGeek** [Platun0v/yandex_music_statistics#3]
File "downloader.py", line 25
    main_url = f'https://yandex.ru'
Вот эта буква f перед почти всеми "строками" вызывает синтаксическую ошибку. Убрал их, и получаю другую ошибку. Поскольку в питоне не шарю, то могу предположить что либо эти f-ы появились из-за кодировки, либо не была подключена/загружена какая-то библиотека. Запускал в cygwin, windows 7, ubuntu 18, всё одинаково. (| = перенос строки)
`Traceback (most recent call last):|
  File "downloader.py", line 200, in <module>|
    yandex.auth()|
  File "downloader.py", line 44, in auth|
    auth_page = self.get('/auth').text|
  File "downloader.py", line 146, in get|
    return self.method('GET', '{self.main_url}/{url if url[0] != "/" else url[1:]}', params=params, **kwargs)|
  File "downloader.py", line 158, in method|
    resp = self.session.get(url, **kwargs)|
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 543, in get|
    return self.request('GET', url, **kwargs)|
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 530, in request|
    resp = self.send(prep, **send_kwargs)|
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 637, in send|
    adapter = self.get_adapter(url=request.url)|
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 730, in get_adapter|
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))|
requests.exceptions.InvalidSchema: No connection adapters were found for u'{self.main_url}/{url if url[0] != "/" else url[1:]}|'
`

**Comment by ruslangazizov** [comment]
@TkachGeek Кажется буква f перед строками вызывает синтаксическую ошибку из-за того, что вы используете питон версии 2. Попробуйте скачать третью версию.
